"use client";

import { BrainCircuit } from "lucide-react";

export default function AIQuestionGeneratorPage() {
  return (
    <main className="min-h-screen bg-slate-100 p-8">

      <div className="mx-auto max-w-7xl">

        <div className="mb-8 flex items-center gap-3">
          <BrainCircuit className="h-9 w-9 text-blue-600" />

          <div>
            <h1 className="text-3xl font-bold">
              AI Question Generator
            </h1>

            <p className="text-slate-500">
              Generate NEET, JEE and CBSE questions using AI.
            </p>
          </div>
        </div>

        <div className="grid gap-8 lg:grid-cols-3">

          {/* Left */}

          <div className="rounded-2xl bg-white p-6 shadow">

            <h2 className="mb-5 text-xl font-semibold">
              Generate Questions
            </h2>

            <p className="text-slate-500">
              Form will be added in the next step.
            </p>

          </div>

          {/* Right */}

          <div className="lg:col-span-2 rounded-2xl bg-white p-6 shadow">

            <h2 className="mb-5 text-xl font-semibold">
              Generated Questions
            </h2>

            <div className="rounded-xl border-2 border-dashed border-slate-300 p-10 text-center text-slate-400">

              Questions generated by Gemini AI will appear here.

            </div>

          </div>

        </div>

      </div>

    </main>
  );
}