"use client";

import type { QuestionBank } from "@/types/question-bank";

import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import EntitySelect from "@/components/common/EntitySelect";

import {
  QuestionStatus,
  SourceTypes,
  AIProviders,
  DefaultAssessment,
} from "@/constants/question-workspace";

import { useQuestion } from "../hooks/useQuestion";

export default function AssessmentStep() {
  const { question, updateQuestion } = useQuestion();

  const statuses = QuestionStatus.map((item) => ({
    id: item,
    name: item,
  }));

  const sources = SourceTypes.map((item) => ({
    id: item,
    name: item,
  }));

  const providers = AIProviders.map((item) => ({
    id: item,
    name: item,
  }));

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-semibold">
          Assessment Settings
        </h2>

        <p className="mt-1 text-slate-500">
          Configure marks and workflow.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <Label>Marks</Label>

          <Input
            type="number"
            value={
              question.marks ??
              DefaultAssessment.marks
            }
            onChange={(e) =>
              updateQuestion({
                marks: Number(e.target.value),
              })
            }
          />
        </div>

        <div>
          <Label>Negative Marks</Label>

          <Input
            type="number"
            value={
              question.negative_marks ??
              DefaultAssessment.negativeMarks
            }
            onChange={(e) =>
              updateQuestion({
                negative_marks: Number(
                  e.target.value
                ),
              })
            }
          />
        </div>

        <div>
          <Label>
            Estimated Time (Seconds)
          </Label>

          <Input
            type="number"
            value={
              question.estimated_time_seconds ??
              DefaultAssessment.estimatedTimeSeconds
            }
            onChange={(e) =>
              updateQuestion({
                estimated_time_seconds: Number(
                  e.target.value
                ),
              })
            }
          />
        </div>

        <EntitySelect
          label="Source"
          value={question.source_type ?? ""}
          options={sources}
          optionLabel="name"
          optionValue="id"
          onChange={(value) =>
            updateQuestion({
              source_type: value,
            })
          }
        />

        <EntitySelect
          label="Generated By"
          value={question.generated_by ?? ""}
          options={providers}
          optionLabel="name"
          optionValue="id"
          onChange={(value) =>
            updateQuestion({
              generated_by: value,
            })
          }
        />

        <EntitySelect
          label="Status"
          value={question.status ?? "Draft"}
          options={statuses}
          optionLabel="name"
          optionValue="id"
          onChange={(value) =>
            updateQuestion({
              status:
                value as QuestionBank["status"],
            })
          }
        />
      </div>
    </div>
  );
}