"use client";

import { Button } from "@/components/ui/button";

import { useQuestion } from "../hooks/useQuestion";

export default function ReviewStep() {
  const { question } = useQuestion();

  return (
    <div className="space-y-8">

      <div>

        <h2 className="text-2xl font-semibold">
          Review Question
        </h2>

        <p className="mt-1 text-slate-500">
          Review all information before saving the question.
        </p>

      </div>

      {/* Academic Information */}

      <div className="rounded-lg border p-5">

        <h3 className="mb-4 text-lg font-semibold">
          Academic Information
        </h3>

        <div className="grid grid-cols-2 gap-4">

          <Info
            label="Subject ID"
            value={question.subject_id}
          />

          <Info
            label="Chapter ID"
            value={question.chapter_id}
          />

          <Info
            label="Topic ID"
            value={question.topic_id}
          />

          <Info
            label="Difficulty"
            value={question.difficulty_level_id}
          />

          <Info
            label="Bloom Level"
            value={question.bloom_level_id}
          />

          <Info
            label="Question Type"
            value={question.question_type_id}
          />

        </div>

      </div>

      {/* Question */}

      <div className="rounded-lg border p-5">

        <h3 className="mb-4 text-lg font-semibold">
          Question
        </h3>

        <p className="whitespace-pre-wrap">
          {question.question_text || "-"}
        </p>

        <div className="mt-6 space-y-2">

          <Option
            label="A"
            value={question.option_a}
          />

          <Option
            label="B"
            value={question.option_b}
          />

          <Option
            label="C"
            value={question.option_c}
          />

          <Option
            label="D"
            value={question.option_d}
          />

        </div>

        <div className="mt-6">

          <strong>Correct Answer : </strong>

          <span>
            {question.correct_answer ?? "-"}
          </span>

        </div>

      </div>

      {/* Learning */}

      <div className="rounded-lg border p-5">

        <h3 className="mb-4 text-lg font-semibold">
          Learning Support
        </h3>

        <Section
          title="Answer Key"
          value={question.answer_key}
        />

        <Section
          title="Explanation"
          value={question.explanation}
        />

        <Section
          title="Hint"
          value={question.hint}
        />

        <Section
          title="Learning Objective"
          value={question.learning_objective}
        />

      </div>

      {/* Assessment */}

      <div className="rounded-lg border p-5">

        <h3 className="mb-4 text-lg font-semibold">
          Assessment
        </h3>

        <div className="grid grid-cols-2 gap-4">

          <Info
            label="Marks"
            value={question.marks}
          />

          <Info
            label="Negative Marks"
            value={question.negative_marks}
          />

          <Info
            label="Time (Seconds)"
            value={
              question.estimated_time_seconds
            }
          />

          <Info
            label="Status"
            value={question.status}
          />

          <Info
            label="Source"
            value={question.source_type}
          />

          <Info
            label="Generated By"
            value={question.generated_by}
          />

        </div>

      </div>

      {/* Validation */}

      <div className="rounded-lg border border-blue-200 bg-blue-50 p-5">

        <h3 className="mb-3 text-lg font-semibold">
          Validation Checklist
        </h3>

        <ul className="space-y-2 text-sm">

          <Check
            ok={!!question.subject_id}
            text="Subject Selected"
          />

          <Check
            ok={!!question.chapter_id}
            text="Chapter Selected"
          />

          <Check
            ok={!!question.topic_id}
            text="Topic Selected"
          />

          <Check
            ok={!!question.question_text}
            text="Question Entered"
          />

          <Check
            ok={!!question.correct_answer}
            text="Correct Answer Selected"
          />

        </ul>

      </div>

      {/* Actions */}

      <div className="flex flex-wrap gap-4 justify-end">

        <Button variant="outline">
          Save Draft
        </Button>

        <Button variant="secondary">
          Improve with AI
        </Button>

        <Button>
          Publish Question
        </Button>

      </div>

    </div>
  );
}

function Info({
  label,
  value,
}: {
  label: string;
  value: string | number | boolean | null | undefined;
}) {
  return (
    <div>
      <p className="text-sm text-slate-500">
        {label}
      </p>

      <p className="font-medium">
        {value ?? "-"}
      </p>
    </div>
  );
}

function Section({
  title,
  value,
}: {
  title: string;
  value?: string | null;
}) {
  return (
    <div className="mb-5">

      <h4 className="font-medium mb-2">
        {title}
      </h4>

      <p className="whitespace-pre-wrap rounded border bg-slate-50 p-3">
        {value || "-"}
      </p>

    </div>
  );
}

function Option({
  label,
  value,
}: {
  label: string;
  value?: string | null;
}) {
  return (
    <div className="rounded border p-3">

      <strong>{label}.</strong>{" "}

      {value || "-"}

    </div>
  );
}

function Check({
  ok,
  text,
}: {
  ok: boolean;
  text: string;
}) {
  return (
    <li className="flex items-center gap-2">

      <span>
        {ok ? "✅" : "❌"}
      </span>

      <span>{text}</span>

    </li>
  );
}